image: node:12.14.0

stages:
  - test

test:
  stage: test
  tags:
  - developer
  script:
    - echo "Test start"
    - npm set registry https://registry.npm.taobao.org
    - npm ci
    - echo "Test over"
